"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*la-va@b(5t7)kmo+om$&0d0prlhh@qaztwr+3!26dgsa@quuv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".vercel.app", "your-backend-domain.com"]


# ===============================================
# DATABASE CONFIGURATION (Supabase/Vercel)
# ===============================================

# 1. Attempt to get the database URL from the environment.
# Try multiple possible environment variable names
DATABASE_URL = os.getenv('DATABASE_URL') 
if not DATABASE_URL:
    DATABASE_URL = os.getenv('POSTGRES_URL_NON_POOLING')
if not DATABASE_URL:
    DATABASE_URL = os.getenv('POSTGRES_URL')
    
# 2. Check if a valid database URL was found
if DATABASE_URL and DATABASE_URL.strip():  # Added check for empty string
    try:
        # IMPORTANT: Remove query params (like pooling config) as they confuse Django/dj_database_url
        if '?' in DATABASE_URL:
            DATABASE_URL = DATABASE_URL.split('?')[0]
        
        # IMPORTANT: Replace pooling port (6543) with the direct port (5432) for Django
        # Also handle cases where the URL uses port 6543 for pooling
        DATABASE_URL = DATABASE_URL.replace(":6543", ":5432")
        # If using POSTGRES_URL (pooled), ensure we're using direct connection
        if 'pooler' in DATABASE_URL or ':6543' in DATABASE_URL:
            DATABASE_URL = DATABASE_URL.replace(":6543", ":5432")
        
        # 3. Use the parsed, cleaned URL for the default database connection.
        DATABASES = {
            'default': dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=600,
                ssl_require=True
            )
        }
        print("✓ Connected to production database")
    except Exception as e:
        print(f"Error parsing DATABASE_URL: {e}")
        print(f"DATABASE_URL value: {DATABASE_URL[:50]}...")  # Only show first 50 chars for security
        # Fallback to SQLite if parsing fails
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # 4. Fallback for Local Development (if no DATABASE_URL is found)
    print("Warning: DATABASE_URL not found. Falling back to local SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ===============================================
# END DATABASE CONFIGURATION
# ===============================================


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "driver_log",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# ... (rest of the settings remain unchanged)

# ... (the rest of your settings file continues here) ...

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"