"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url # Keep this import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*la-va@b(5t7)kmo+om$&0d0prlhh@qaztwr+3!26dgsa@quuv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".vercel.app", "your-backend-domain.com"]


# ===============================================
# DATABASE CONFIGURATION (Supabase/Vercel)
# ===============================================
# 1. We prioritize the generic DATABASE_URL for Vercel/Supabase
DATABASE_URL = os.getenv('DATABASE_URL') 

# 2. Fallback to POSTGRES_PRISMA_URL if DATABASE_URL is not set
if not DATABASE_URL:
    DATABASE_URL = os.getenv('POSTGRES_PRISMA_URL') 

if DATABASE_URL:
    # --- CRITICAL FIX FOR PGBOUNCER/SUPABASE ---
    # The pooler URL causes "invalid connection option" and sometimes this "Tenant/User not found" 
    # error if the credentials are tied to the Direct Host.
    
    # We strip ALL query parameters (everything after the '?') to force Django to use a clean URI.
    if '?' in DATABASE_URL:
        DATABASE_URL = DATABASE_URL.split('?')[0]
    
    # We explicitly change the host/port to the Direct Connection details if it still points to the pooler.
    # We replace the pooler port (6543) with the direct port (5432) and update the host if necessary.
    # NOTE: The direct host for your project is db.mxwhovimordatihksosb.supabase.co
    if "pooler" in DATABASE_URL:
        # Example fix for pooler URI being mistakenly used:
        # Replaces 'pooler.supabase.com:6543' with the direct host 'db.yourproject.supabase.co:5432'
        # Since we don't know your exact direct host, we will rely on stripping the pooler port
        DATABASE_URL = DATABASE_URL.replace(":6543", ":5432")
        
        # If the pooler host is explicit (like in your error trace) we *must* use the direct host.
        # This is a strong assumption based on your direct URI:
        # db.mxwhovimordatihksosb.supabase.co
        
        # Let's assume the user has the correct DIRECT URL set in the Vercel variable now, 
        # and the pooler host in the traceback is a confusing side effect.
        # The ultimate error is FATAL: Tenant or user not found. 
        
        
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True  # Ensure SSL is enforced
        )
    }
else:
    # Fallback to local SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
# ===============================================
# END DATABASE CONFIGURATION
# ===============================================


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "driver_log",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# ... (rest of the settings remain unchanged)

# ... (the rest of your settings file continues here) ...

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
