# Generated by Django 5.2.6 on 2025-09-26 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                (
                    "pickup_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "current_cycle_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("calculated_route_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_sheet_date", models.DateField()),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("OFF", "Off Duty"),
                            ("SB", "Sleeper Berth"),
                            ("DR", "Driving"),
                            ("ON", "On Duty"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "start_location_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "end_location_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "distance_driven",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="driver_log.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["log_sheet_date", "start_time"],
            },
        ),
    ]
