# Generated by Django 5.2.6 on 2025-09-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="adverse_conditions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_interval_miles",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_property_carrying",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="service_time_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
